version: '3'
services:
  lextoolf-front:
    image: lextoolf-front
    restart: always
    build:
      context: .
    network_mode: bridge
    environment:
      - VUE_APP_MINIO_URL='http://10.25.27.77:9021/files'
      - VUE_APP_BACKEND_URL='http://10.25.27.77:9021/graphql'
    ports:
      - 9022:80
      