/**
 * Generated by GENERATOR
 * Date: 10/21/2020, 11:36:54 AM
 **/

import { userFragment } from './fragments';
import { apolloClient } from '../../apolloProvider';

export const readUserFromCache = (id, variables = {}) => {
  const userFragmentData = getUserDataFragment(id, variables);
  const user = apolloClient.readFragment(userFragmentData);
  if (!user) {
    debugger;
  }
  return user;
};

export const writeUserOnCache = (data, variables = {}) => {
  const userFragmentData = getUserDataFragment(data._id, variables);
  apolloClient.cache.writeFragment({
    ...userFragmentData,
    data,
  });
};

const getUserDataFragment = (id, variables) => {
  return {
    id: 'User_' + id,
    fragment: userFragment,
    fragmentName: 'userFragment',
    variables,
  };
};
