/**
 * Generated by GENERATOR
 * Date: 10/21/2020, 11:36:54 AM
 **/

export class CreateUserInput {
  public name: string;
  public email: string;
  public password: string;
}

export class UpdateUserInput {
  public _id: string;
  public name?: string;
  public address?: object;
  public imgProfile?: string;
  public description?: string;

  constructor(data?: Partial<UpdateUserInput>) {
    if (data) {
      this.name = data.name;
      this.address = data.address;
      this.imgProfile = data.imgProfile;
      this.description = data.description;
      this._id = data._id;
    }
  }
}
