export const SCRIPTS = [
  'lib/jquery/jquery.js',
  // 'lib/mdb/mdb.min.js',
  // 'lib/popper.js/popper.js',
  // 'lib/bootstrap/bootstrap.js',
  'lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js',
  // 'lib/moment/moment.js',
  // 'lib/jquery-ui/jquery-ui.js',
  // 'lib/jquery-switchbutton/jquery.switchButton.js',
  // 'lib/peity/jquery.peity.js',
  // 'lib/chartist/chartist.js',
  // 'lib/jquery.sparkline.bower/jquery.sparkline.min.js',
  // 'lib/d3/d3.js',
  // 'lib/rickshaw/rickshaw.min.js',
  'js/main.js',
  // 'js/ResizeSensor.js',
  // 'js/widgets.js',
];
